### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Clermonder** [syssi/chuangmi_ir#12]
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 82, in async_setup
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/switch/chuangmi_ir.py", line 77, in setup_platform
    ir_remote = Device(host, token, lazy_discover=False)
NameError: name 'Device' is not defined

this is the log  ha==0.65.6  miio==0.3.7
I know the remote.xiaomi_miio, but I think the type of switch is better :)

**Comment by syssi** [comment]
Should be fixed! Give it a try. :-)
