### ISSUE TITLE
Not working with python-miio 0.3.3

### ISSUE THREAD

**Issue by Weetab1x** [syssi/chuangmi_ir#9]
Seems like there is something with the new python-miio that is not working with chuangmi_ir right now.

```
2017-12-31 07:49:47 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/switch/chuangmi_ir.py", line 173, in _sendpacket
    self._device.send("miIO.ir_play", {'freq':38400, 'code': str(packet)})
  File "/srv/homeassistant/lib/python3.5/site-packages/miio/device.py", line 198, in send
    self.do_discover()
  File "/srv/homeassistant/lib/python3.5/site-packages/miio/device.py", line 138, in do_discover
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.device.DeviceException: Unable to discover the device 192.168.31.45

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1031, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/switch/__init__.py", line 113, in async_handle_switch_service
    yield from switch.async_turn_on()
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/switch/chuangmi_ir.py", line 157, in turn_on
    if self._sendpacket(self._command_on):
  File "/home/homeassistant/.homeassistant/custom_components/switch/chuangmi_ir.py", line 174, in _sendpacket
    except (socket.timeout, ValueError) as error:
NameError: name 'socket' is not defined
```

**Comment by syssi** [comment]
Did you install python-miio=0.3.3 manually and start homeassistant with skip-pip? Otherwise a old requirement was fetched probably. Could you please check the version of

/srv/homeassistant/lib/python3.5/site-packages/miio

twice? This isn't version 0.3.3, right?

**Comment by Weetab1x** [comment]
I'm sorry, I should have been clearer. 

```
pi@hassbian:/srv/homeassistant/lib/python3.5/site-packages/miio $ cat version.py
# flake8: noqa
__version__ = "0.3.3"
```

I am on developer branch for home assistant to sort a problem with miio/protocol.py and a few devices. I also did a pip3 install python-miio==0.3.3 while trying to fix the problem.

So I am guessing that the protocol.py is updated and that has broken chuangmi_ir.

**Comment by syssi** [comment]
This is strange. I will try to reproduce the issue. Thanks for your report!

**Comment by Weetab1x** [comment]
Super embarrassing, almost to the point I don't want to talk about it. The vacuum robot had pulled the plug on the IR box. So, this is not an issue, poor cable management is.

Let me buy you a beer.

**Comment by syssi** [comment]
lol. I will close the issue! :-)
